### PR TITLE
Unify old TSDB version cleanup code

### PR DESCRIPTION
**Pull request by jnidzwetzki**
Removed dead code to delete version 1.x TSDB versions and keep old versions in the Bitnami image.

Fixes: #232

### CODE REVIEW

**Review by svenklemm — CHANGES_REQUESTED** [review]
This is a regression as it previously was only deleting 1.x versions which was dead code  because they are not part of any update path that is valid for current versions.

**Comment by jnidzwetzki** [comment]
@svenklemm I am not sure if I get your point entirely. The new code restricts the copied TSDB versions to 5 (we do the same in the Bitnami image). Do you think we should remove this step? In this case, the image would become larger with every version.

**Comment by svenklemm** [comment]
Only deleting stuff from the 1.0 series was intentional afair. Image size is limited by pg version support with older versions having bigger images. Having all versions available is a plus as you might need it when using an old database that has not yet been updated.

**Comment by jnidzwetzki** [comment]
@svenklemm I reverted my changes and removed only the dead code. I also adjusted the bitnami image and applied the same logic to keep the old versions.

**Pull request merged**
