### PR TITLE
Using newer postgis

### PR DESCRIPTION
**Pull request by tsl-karlp**

### CODE REVIEW

**Comment by RobAtticus** [comment]
Can you update this PR to change the default version in the Makefile for PG 9.6 to 2.3.7 as well?

**Comment by RobAtticus** [comment]
Also if you could merge into one commit that would be best. Much appreciated!

**Comment by tsl-karlp** [comment]
@RobAtticus : I don't mind squashing and repushing, but can't you guys squash and merge from [the Github UI](https://blog.github.com/2016-04-01-squash-your-commits/#whats-changing)?

**Comment by RobAtticus** [comment]
We can, but haven't not done it I wasn't sure how much control I had over e.g. the commit message.

**Comment by RobAtticus** [comment]
Looks like I may have a fair bit, so no worries

**Pull request merged**
