### PR TITLE
Add TS_TUNE_MAX_CONNS environment variable

### PR DESCRIPTION
**Pull request by jflambert**
Closes [timescaledb-tune #54](https://github.com/timescale/timescaledb-tune/issues/54)

### CODE REVIEW

**Review by RobAtticus — APPROVED** [review]

**Comment by RobAtticus** [comment]
@k-rus will let you decide how/when to merge this

**Review by svenklemm — APPROVED** [review]

**Comment by JakeCooper** [comment]
Anyway to get a 2.1.1 release cut for this?

**Comment by RobAtticus** [comment]
Don't think a new version is needed, just a new image published

**Comment by jflambert** [comment]
> Anyway to get a 2.1.1 release cut for this?

It's definitely in 2.1.0, just pull again

**Pull request merged**
